### ISSUE TITLE
Propose a new rule. Use Nullish coalescing operator (??) instead of logical OR (||)

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/quality-criteria#12]
## Problem

There is a problem that people do not use logical OR (`||`) and nullish coalescing (`??`) in the right situations.

```ts
const x = 0;

x || 'default' // 'default'
x ?? 'default'  // 0
```

## Proposal

Add a new rule that will force these operators to be used correctly `||` (only with booleans) ?? (only with `null` and `undefined` ).

**Comment by what1s1ove** [comment]
Totally agree that we need such a rule. My only point is forcing people to use new constructs (for example, `user?.name` instead `user && user.name`). Maybe we should add a general rule something like "use modern syntax". Thoughts?

More examples

```ts
await fn();

// vs

(async () => {
  await fn();
})();
```

```ts
arr.slice().sort();

// vs

arr.toSorted();
```

**Comment by viacheslav-iskenderov** [comment]
Agreed with @what1s1ove, though I'm not so sure about `?.`. I agree with `user?.name`, but don't like calling method that might not exist this way. I would prefer having something like `if (instance.method) instance.method()` rather than `instance.method.?()`

**Comment by nikita-remeslov** [comment]
I think it's worth making common examples of old and new syntax. And thus force the use of the new syntax

**Comment by what1s1ove** [comment]
> Agreed with @what1s1ove, though I'm not so sure about `?.`. I agree with `user?.name`, but don't like calling method that might not exist this way. I would prefer having something like `if (instance.method) instance.method()` rather than `instance.method.?()`

I think two options are possible. But lets see what the team says 🙂

> I think it's worth making common examples of old and new syntax. And thus force the use of the new syntax

For now I have only two cases in my mind: `??` and `user?.name`. Maybe you have extra 🤔

**Comment by what1s1ove** [comment]
The new rule was added – **A1. Modern syntax is preferred.**

https://github.com/BinaryStudioAcademy/quality-criteria/commit/a173ad9930e70efc4218a26f372e4798ba0fda65
