### ISSUE TITLE
Propose a new rule. Use shortcuts for booleans, but explicit comparisons for other data types

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/quality-criteria#13]
## Problem

The problem is that in JS you can do a lot of things that are implicit.

```ts
// Bad
if (isValid === true) {
  // ...
}
if (array.length) {
  // ...
}
if (number) {
  // ...
}
// ... etc.

// Good
if (isValid) {
  // ...
}
if (array.length > 0) {
  // ...
}
if (number > 0) {
  // ...
}
// ... etc.
```

## Proposal

Force people to do all checks explicitly.

**Comment by what1s1ove** [comment]
Honestly, I also like when all the checks are made explicitly. But it seems to me that this is more a matter of taste and team preferences. But I agree that having one way to do something is better than having several.

Btw, just found an eslint rule to easily handle it – https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md

We need more discussion. Please share your thought below.

**Comment by viacheslav-iskenderov** [comment]
Completely agree with explicit checks 🙂

**Comment by nikita-remeslov** [comment]
The main case that I see in this is that the explicit check of the condition makes the code easier.

Sometimes we don't notice things because the JS allows it.
But if you take strongly typed languages, they force you to do an explicit check.

It also simplifies testing in cases where we return data and use it as a boolean flag.

**Comment by what1s1ove** [comment]
Hey @nikita-remeslov 

> But if you take strongly typed languages, they force you to do an explicit check.

But we use JS, right? 😃

> - The main case that I see in this is that the explicit check of the condition makes the code easier. 
> - It also simplifies testing in cases where we return data and use it as a boolean flag.

Completely agree with these points! Let's see what the team says!

**Comment by what1s1ove** [comment]
Hello team,

After discussions with the team, we did not come to a consensus. 50% for explicit verification, 50% against. I think we need to discuss this at this academy and decide with the team what is best.

For now, all teams that want explicit checks (including me) can use the rule I posted above.
