### ISSUE TITLE
Propose a new rule. Use curly and return instead of large lambda expressions

### ISSUE THREAD

**Issue by v0ldemar01** [BinaryStudioAcademy/quality-criteria#14]
## Problem
There is a problem that people prefer using lambda expressions than arrow functions. If the prettier is enabled it will move into new line and it will decrease readness.

```js
const foo = (someArrayToIterate, existingValue) => (propertyToCheck) =>  
    someArrayToIterate.map(element => element === existingValue || !propertyToCheck)
```

## Proposal

Add a new rule that will force to add `curly` and `return`  for large expressions to increase readness

```js
const foo = (someArrayToIterate, existingValue) => {
    return (propertyToCheck) =>  {
        return someArrayToIterate.map(element => element === existingValue || !propertyToCheck)
    }
}
    
```

**Comment by what1s1ove** [comment]
Hey @v0ldemar01 !
I agree, it looks bad but I think it's more about style (eslint & prettier). The quality criteria is not about the code readability. It is more about the correctness. But I opened to any suggestions 🙂

**Comment by what1s1ove** [comment]
Hello team!

After discussion with the team, we decided that this is a stylistic rule and each team should decide for itself what it likes.
