### ISSUE TITLE
JavaScript Criteria Fix Proposals

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/quality-criteria#15]
**1. B29**
The name of the variable can be confusing. I think UsersAction would be clearer, since it is an enum, not a type.
![image](https://github.com/BinaryStudioAcademy/quality-criteria/assets/61088675/a1da7440-8966-4e16-8dd2-37b0f7254a1f)

**2. B30**
Typo in the name of variable.
![image](https://github.com/BinaryStudioAcademy/quality-criteria/assets/61088675/1f33c09e-b9b6-4d70-b7e6-89625f1499c1)

**3. B36**
According to B22, constant names should be capitalized. So maybe it should be `const GREETING = '...';`?
![image](https://github.com/BinaryStudioAcademy/quality-criteria/assets/61088675/97372247-193a-4457-9b00-97d85a5eb961)

**Comment by what1s1ove** [comment]
Hey @fshabanov ,
Thank you for participation!
1, 2 – thanks! Pushed changes! In the future, for any grammar/logical mistakes, feel free to create PRs 👍
3 – it is not a constant, it's just an example 🙂 at least we are mutating it 😁
