### ISSUE TITLE
Clarification for JS B29 rule

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/quality-criteria#19]
>  Sets of constants of the same type are collected into Enums.

Does this mean that we can't collect values of different type into Enum? like this

```typescript
const ProjectPrefix = {
  APP: 'BSA',
  ENVIRONMENTS: ['production'],
} as const;

export { ProjectPrefix };
```

**Comment by what1s1ove** [comment]
Hello @Liza-Veis,
For me they are all project prefixes, isn't it? So it's an enum, I guess 🙂

**Comment by liza-veis** [comment]
but they have different data types. The rule sounds correct to me, but this structure that we use for ProjectProfixes are incorrect according to it

**Comment by what1s1ove** [comment]
> but they have different data types. The rule sounds correct to me, but this structure that we use for ProjectProfixes are incorrect according to it

I guess it's okay for enums to have different data types. They must have the same meaning.
