### ISSUE TITLE
Clarification for JS B31 rule

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/quality-criteria#20]
What about values that is used for example to check that array is empty? Should such numbers also be considered as magic number?

**Comment by what1s1ove** [comment]
Hello @Liza-Veis,
Yes, I think so. Something like this

```ts
const isEmpty = items.length === EMPTY_ARRAY_LENGHT_COUNT;
```

**Comment by liza-veis** [comment]
Ok, got this
