### ISSUE TITLE
Fix some misspellings

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/quality-criteria#25]
1. **JS B21**
enum name -> class name

2. **JS B45**
> Migrations roll without errors in two ways (up and down) without any errors.

should be

> Migrations roll in two ways (up and down) without any errors.

3.  **JS A1**
`user.user.name` -> `user.name`

3.  **JS A9**
List items should start on a new line each
<img width="953" alt="Screenshot 2023-08-13 at 14 35 06" src="https://github.com/BinaryStudioAcademy/quality-criteria/assets/64521658/f7d9e893-9051-49ed-8680-f8e855dd34de">

**Comment by what1s1ove** [comment]
Hello @Liza-Veis,
Good catch, thanks!
Could you create a PR for all these mistakes, please?

What about **A9**, delete this description at all. All prop-cbs should be names always with `on` prefix.

**Comment by what1s1ove** [comment]
https://github.com/BinaryStudioAcademy/quality-criteria/pull/29
