### ISSUE TITLE
B21. Class names that contains acronyms

### ISSUE THREAD

**Issue by viacheslav-iskenderov** [BinaryStudioAcademy/quality-criteria#7]
Add a note about naming rules for class names containing acronyms. The first acronym in the name must be capitalized, all others must have only the first letter capitalized.
Examples: `JSON`, `XMLHttpRequest`, `HTMLMediaElement` etc.
(Maybe it's a very edgy case, but had a long discussion about that in the team not long ago, and it would be great if there was a not about that at least somewhere)

**Comment by what1s1ove** [comment]
Hey @viacheslav-iskenderov,

Thank you for participating! Agreed with this: _The first acronym in the name must be capitalized, all others must have only the first letter capitalized._ Btw, I think we need to apply it for both enums (**B23**) and classes (**B21**)

Do you want to contribute? Feel free to create the PR 👍
