### ISSUE TITLE
Fixes for JS criteria. Add new rules

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/quality-criteria#8]
### 1. B36
Looks like additional info is missed here
![image](https://github.com/BinaryStudioAcademy/quality-criteria/assets/78347072/5bc10903-bc10-4dcd-afb4-b4e0154a7f00)

### 2. B38
B38 is repeated 2 times.
![image](https://github.com/BinaryStudioAcademy/quality-criteria/assets/78347072/f739693e-a77c-44ae-a118-c1753d0e05e4)

### 3. A14
Looks redundant. As for me, it contradicts A16. It is worth making an example with a different data type. Since for an array it is better to use array methods.

### 4. A11
If you comply with criterion B19, then the variable should be named `isMale`
![image](https://github.com/BinaryStudioAcademy/quality-criteria/assets/78347072/01e7ac0e-bb32-439f-a248-cbb5d4e1bf93)

### 5. Use Nullish coalescing operator (??) instead of  logical OR (||)
```js
const x = 0;

x || 'default' // 'default'
x ?? 'default'  // 0
```

### 6. Use shortcuts for booleans, but explicit comparisons for other data types
```js
// Bad
if (isValid === true) {
  // ...
}
if (array.length) {
  // ...
}
if (number) {
  // ...
}
// ... etc.

// Good
if (isValid) {
  // ...
}
if (array.length > 0) {
  // ...
}
if (number > 0) {
  // ...
}
// ... etc.
```

**Comment by what1s1ove** [comment]
Hey @nikita-remeslov 

- 1, 2, 4 - fixed, thanks! In the future – feel free to create PRs for any grammar mistakes.
- 3 - Do not forget that JS has pseudo arrays (ex. `querySelector` returns a pseudo array (you cannot user array methods on that array)). **A14** is most about such cases.
- 5 - [converted to new issue](https://github.com/BinaryStudioAcademy/quality-criteria/issues/12)
- 6 - [converted to new issue](https://github.com/BinaryStudioAcademy/quality-criteria/issues/13)

**Comment by nikita-remeslov** [comment]
@what1s1ove 
I think to make it more clear, it is better to make an example for this item with a different data type.

> 3. A14
Looks redundant. As for me, it contradicts A16. It is worth making an example with a different data type. Since for an array it is better to use array methods.

**Comment by what1s1ove** [comment]
All sub issues were closed! Thanks, team!
